hosts:
  host: 'http://localhost:8000'
  static: 'http://localhost:8001'
paths:
  templates:
    root: 'templates'
    article: 'blog/article.pug'
    plain: 'blog/plain.pug'
    projects: 'projects/index.pug'
  data:
    root: 'data'
    articles: 'articles'
    projects: 'projects.yaml'
  public:
    root: 'public'
    articles: 'blog'
    projects: 'projects'

