hosts:
  host: 'https://adamheins.com'
  static: 'https://static.adamheins.com'
paths:
  templates:
    root: '/home/adam/dev/proj/adamheins.com/templates'
    article: 'blog/article.pug'
    plain: 'blog/plain.pug'
    projects: 'projects/index.pug'
  data:
    root: 'data'
    articles: 'articles'
    projects: 'projects.yaml'
  public:
    root: 'public'
    articles: 'blog'
    projects: 'projects'

