hosts:
  host: 'https://adamheins.com'
  static: 'https://static.adamheins.com'
paths:
  templates:
    root: 'templates'
    article: 'templates/blog/article.pug'
    projects: 'templates/projects/index.pug'
  articles: 'data/articles'
  projects: 'data/projects.yaml'
  public: 'public'

