hosts:
  host: 'https://adamheins.com'
  static: 'https://static.adamheins.com'
paths:
  templates:
    root: 'templates'
    article: 'templates/blog/article.pug'
  articles: 'articles'
  public: 'public'

